#pragma config(Sensor, S1,     sound,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int clapCount = 0;

	while(true)
	{

		displayBigTextLine(4,"var: %d", clapCount);

		while(SensorValue(sound) < 50)
		{
		}
			if(SensorValue(sound) > 50)
			motor[motorA] = 50;
			wait1Msec(500);
			motor[motorA] = 0;

		clapCount = clapCount + 1;
		displayBigTextLine(4,"var: %d", clapCount);

		while(SensorValue(sound) < 50)
		{
		}
			if(SensorValue(sound) > 50)
			motor[motorA] = -50;
			wait1Msec(500);
			motor[motorA] = 0;

		clapCount = clapCount + 1;
	}
}
